/**
 * Generates frontend/lib/qr-logo-mask.js from the SFLuv mark.
 *
 * The QR's centre clearing follows the mark's actual silhouette rather than a
 * circle, so the moat hugs the letterform instead of punching a round hole
 * around it. That needs the mark's alpha channel as data the renderer can read
 * synchronously on every platform, so it is baked out here rather than decoded
 * at runtime.
 *
 * Also measures the mark's placement inside its own asset. icon.png is not
 * centred on its ink — the artwork sits high and is inset all round — and both
 * facts have to be corrected for or the mark renders visibly above centre with
 * an uneven gap.
 *
 * Run: node gen_qr_logo_mask.js   (only needed if the logo asset changes)
 */
const fs = require("fs")
const path = require("path")
const zlib = require("zlib")

const SOURCE = path.join(__dirname, "frontend/public/icon.png")
const OUT = path.join(__dirname, "frontend/lib/qr-logo-mask.js")
/** Mask resolution. Each cell is ~1.5% of the mark, finer than a QR module. */
const GRID = 64
/** A cell counts as ink at this coverage. */
const COVERAGE = 0.18
const ALPHA_FLOOR = 8

function decodePNG(file) {
  const buf = fs.readFileSync(file)
  let p = 8
  const idat = []
  let width = 0
  let height = 0
  let colorType = 0
  let bitDepth = 0
  while (p < buf.length) {
    const len = buf.readUInt32BE(p)
    const type = buf.toString("ascii", p + 4, p + 8)
    if (type === "IHDR") {
      width = buf.readUInt32BE(p + 8)
      height = buf.readUInt32BE(p + 12)
      bitDepth = buf[p + 16]
      colorType = buf[p + 17]
    }
    if (type === "IDAT") idat.push(buf.slice(p + 8, p + 8 + len))
    p += 12 + len
    if (type === "IEND") break
  }
  if (colorType !== 6 || bitDepth !== 8) {
    throw new Error(`gen_qr_logo_mask: expected 8-bit RGBA, got colorType ${colorType} depth ${bitDepth}`)
  }
  const raw = zlib.inflateSync(Buffer.concat(idat))
  const bpp = 4
  const stride = width * bpp
  const out = Buffer.alloc(height * stride)
  let pos = 0
  for (let y = 0; y < height; y++) {
    const filter = raw[pos++]
    const line = raw.slice(pos, pos + stride)
    pos += stride
    for (let x = 0; x < stride; x++) {
      const a = x >= bpp ? out[y * stride + x - bpp] : 0
      const b = y > 0 ? out[(y - 1) * stride + x] : 0
      const c = x >= bpp && y > 0 ? out[(y - 1) * stride + x - bpp] : 0
      let v = line[x]
      if (filter === 1) v += a
      else if (filter === 2) v += b
      else if (filter === 3) v += (a + b) >> 1
      else if (filter === 4) {
        const pa = Math.abs(b - c)
        const pb = Math.abs(a - c)
        const pc = Math.abs(a + b - 2 * c)
        v += pa <= pb && pa <= pc ? a : pb <= pc ? b : c
      }
      out[y * stride + x] = v & 255
    }
  }
  return { width, height, stride, data: out }
}

const png = decodePNG(SOURCE)
const alpha = (x, y) => png.data[y * png.stride + x * 4 + 3]

// Where the ink actually sits inside the asset.
let minX = png.width
let minY = png.height
let maxX = -1
let maxY = -1
let sumX = 0
let sumY = 0
let inkPixels = 0
for (let y = 0; y < png.height; y++) {
  for (let x = 0; x < png.width; x++) {
    if (alpha(x, y) <= ALPHA_FLOOR) continue
    if (x < minX) minX = x
    if (x > maxX) maxX = x
    if (y < minY) minY = y
    if (y > maxY) maxY = y
    sumX += x
    sumY += y
    inkPixels++
  }
}

const rows = []
for (let gy = 0; gy < GRID; gy++) {
  let row = ""
  for (let gx = 0; gx < GRID; gx++) {
    let covered = 0
    let total = 0
    for (let y = Math.floor((gy * png.height) / GRID); y < ((gy + 1) * png.height) / GRID; y++) {
      for (let x = Math.floor((gx * png.width) / GRID); x < ((gx + 1) * png.width) / GRID; x++) {
        total++
        if (alpha(x, y) > ALPHA_FLOOR) covered++
      }
    }
    row += covered / total >= COVERAGE ? "1" : "0"
  }
  rows.push(row)
}

/** Fractions of the asset's own width/height. */
const markWidth = (maxX - minX + 1) / png.width
const markHeight = (maxY - minY + 1) / png.height
// Optical centring uses the ink centroid, not the bounding box: this mark is
// top-heavy, so box-centring still reads high.
const centroidOffsetY = (sumY / inkPixels - (png.height - 1) / 2) / png.height
const centroidOffsetX = (sumX / inkPixels - (png.width - 1) / 2) / png.width

const file = `/**
 * GENERATED by gen_qr_logo_mask.js from frontend/public/icon.png — do not edit.
 *
 * A ${GRID}x${GRID} silhouette of the SFLuv mark, plus where its ink sits inside
 * its own asset. The QR renderer uses the silhouette to shape the centre
 * clearing to the mark, and the offsets to place the mark on its optical centre.
 *
 * Regenerate with \`node gen_qr_logo_mask.js\` whenever the logo asset changes.
 */
/** Cells per side. */
const MASK_GRID = ${GRID}
/** Row-major, "1" where the mark has ink. */
const MASK_ROWS = [
${rows.map((r) => `  "${r}",`).join("\n")}
]
/** Ink bounding box as a fraction of the asset. */
const MARK_WIDTH = ${markWidth.toFixed(4)}
const MARK_HEIGHT = ${markHeight.toFixed(4)}
/**
 * Ink centroid offset from the asset centre, as a fraction of the asset.
 * Negative Y means the artwork sits high, which is why it must be nudged down.
 */
const MARK_CENTROID_OFFSET_X = ${centroidOffsetX.toFixed(4)}
const MARK_CENTROID_OFFSET_Y = ${centroidOffsetY.toFixed(4)}

module.exports = {
  MASK_GRID,
  MASK_ROWS,
  MARK_WIDTH,
  MARK_HEIGHT,
  MARK_CENTROID_OFFSET_X,
  MARK_CENTROID_OFFSET_Y,
}
`

fs.writeFileSync(OUT, file)

// The mobile app renders the same code and needs the same silhouette. Emitted
// here rather than hand-copied so the two repos cannot fall out of step.
const MOBILE_OUT = path.join(__dirname, "../mobile-app/mobile/src/lib/qrLogoMask.ts")
if (fs.existsSync(path.dirname(MOBILE_OUT))) {
  fs.writeFileSync(MOBILE_OUT, file.replace(/^const /gm, "export const ").replace(/\nmodule\.exports = \{[\s\S]*\}\n$/, "\n"))
  console.log(`wrote ${MOBILE_OUT}`)
} else {
  console.log(`skipped mobile copy — ${path.dirname(MOBILE_OUT)} not present`)
}
console.log(`wrote ${OUT}`)
console.log(`  grid ${GRID}x${GRID}, ink ${(markWidth * 100).toFixed(1)}% x ${(markHeight * 100).toFixed(1)}% of the asset`)
console.log(`  centroid offset x ${centroidOffsetX.toFixed(4)} y ${centroidOffsetY.toFixed(4)} (of the asset)`)
