docker build -t backend_sfluv .
docker tag backend_sfluv:latest us-central1-docker.pkg.dev/sfluv-app/sfluv-images/backend_sfluv:latest
docker push us-central1-docker.pkg.dev/sfluv-app/sfluv-images/backend_sfluv:latest