import { PolicyPageShell } from "@/components/legal/policy-page-shell"
import { PRIVACY_POLICY_LAST_UPDATED } from "@/lib/policies"
import { ReactNode } from "react"

function Section({
  title,
  children,
}: {
  title: string
  children: ReactNode
}) {
  return (
    <section className="space-y-3">
      <h2 className="text-xl font-semibold tracking-tight text-foreground">{title}</h2>
      {children}
    </section>
  )
}

export default function PrivacyPolicyPage() {
  return (
    <PolicyPageShell title="Privacy Policy" lastUpdated={PRIVACY_POLICY_LAST_UPDATED}>
      <p>
        This Privacy Policy describes Our policies and procedures on the collection, use and
        disclosure of Your information when You use the Service and tells You about Your privacy
        rights and how the law protects You.
      </p>
      <p>
        We use Your Personal Data to provide and improve the Service. By using the Service, You
        agree to the collection and use of information in accordance with this Privacy Policy.
      </p>

      <Section title="Interpretation and Definitions">
        <p>
          The words whose initial letters are capitalized have meanings defined under the
          conditions below. The following definitions shall have the same meaning regardless of
          whether they appear in singular or in plural.
        </p>
        <ul className="list-disc space-y-2 pl-6 text-muted-foreground">
          <li>Account means a unique account created for You to access our Service.</li>
          <li>
            Affiliate means an entity that controls, is controlled by, or is under common control
            with a party, where control means ownership of 50% or more of the voting interests.
          </li>
          <li>Application refers to SFLuv Wallet App, the software program provided by the Company.</li>
          <li>
            Business, for the purpose of CCPA/CPRA, refers to the Company as the legal entity that
            collects Consumers' personal information and determines the purposes and means of the
            processing of that information in California.
          </li>
          <li>CCPA and/or CPRA refers to the California privacy laws and amendments.</li>
          <li>Company refers to SFLuv, 445 Baden St.; San Francisco, CA 94131.</li>
          <li>Country refers to California, United States.</li>
          <li>
            Device means any device that can access the Service such as a computer, a cell phone
            or a digital tablet.
          </li>
          <li>
            Personal Data or Personal Information means any information that relates to an
            identified or identifiable individual. We use these terms interchangeably unless a law
            uses a specific term.
          </li>
          <li>Service refers to the Application.</li>
          <li>
            Service Provider means any natural or legal person who processes the data on behalf of
            the Company.
          </li>
          <li>
            Third-Party Social Media Service refers to any website or social network through which
            a User can log in or create an account to use the Service.
          </li>
          <li>
            Usage Data refers to data collected automatically, either generated by the use of the
            Service or from the Service infrastructure itself.
          </li>
          <li>
            You means the individual or legal entity accessing or using the Service, as
            applicable.
          </li>
        </ul>
      </Section>

      <Section title="Collecting and Using Your Personal Data">
        <h3 className="font-semibold text-foreground">Types of Data Collected</h3>
        <p>
          While using Our Service, We may ask You to provide certain personally identifiable
          information, including but not limited to Your email address, first name, last name, and
          Usage Data.
        </p>
        <p>
          Usage Data is collected automatically and may include Your Device's IP address, browser
          type and version, the pages of our Service that You visit, the time and date of Your
          visit, time spent on those pages, unique device identifiers, and other diagnostic data.
        </p>
        <p>
          When You access the Service by or through a mobile device, We may also collect
          information such as the mobile device type, unique device ID, IP address, operating
          system, mobile browser type, and similar diagnostic data.
        </p>
        <p>
          The Company allows You to create an account and log in through Google, Facebook,
          Instagram, X (Twitter), and LinkedIn. If You decide to register through or otherwise
          grant Us access to a Third-Party Social Media Service, We may collect Personal Data
          already associated with that account, such as Your name, email address, activities, or
          contacts.
        </p>
        <p>
          While using Our Application, in order to provide features of Our Application, We may
          collect, with Your prior permission, pictures and other information from your Device's
          camera and photo library. You can enable or disable access at any time through Your
          Device settings.
        </p>
      </Section>

      <Section title="Use of Your Personal Data">
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul className="list-disc space-y-2 pl-6 text-muted-foreground">
          <li>To provide and maintain our Service, including to monitor usage.</li>
          <li>To manage Your Account and Your registration as a user of the Service.</li>
          <li>
            For the performance of a contract, including products, items, and services You
            purchase or request through the Service.
          </li>
          <li>
            To contact You by email, telephone calls, SMS, push notifications, or similar
            electronic communications regarding updates, features, security, and contracted
            services.
          </li>
          <li>
            To provide You with news, special offers, and general information about similar goods,
            services, and events unless You have opted out.
          </li>
          <li>To manage Your requests.</li>
          <li>
            For business transfers, including a merger, divestiture, restructuring, or sale of
            assets.
          </li>
          <li>
            For other purposes such as data analysis, identifying usage trends, evaluating
            promotional campaigns, and improving Our Service, products, services, marketing, and
            Your experience.
          </li>
        </ul>
        <p>We may share Your Personal Data in the following situations:</p>
        <ul className="list-disc space-y-2 pl-6 text-muted-foreground">
          <li>With Service Providers that help Us operate, analyze, or contact You about the Service.</li>
          <li>For business transfers and related negotiations.</li>
          <li>With Affiliates, who must honor this Privacy Policy.</li>
          <li>With business partners for products, services, or promotions.</li>
          <li>
            With other users where Our Service offers public areas and You choose to share
            Personal Data or activity.
          </li>
          <li>With Your consent for any other purpose.</li>
        </ul>
      </Section>

      <Section title="Retention of Your Personal Data">
        <p>
          The Company will retain Your Personal Data only for as long as necessary for the purposes
          set out in this Privacy Policy. We may retain and use Personal Data to comply with legal
          obligations, resolve disputes, and enforce legal agreements and policies.
        </p>
        <p>
          Where possible, We apply shorter retention periods and/or reduce identifiability by
          deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention
          periods below are maximum periods and We may delete or anonymize data sooner when it is
          no longer needed for the relevant purpose.
        </p>
        <ul className="list-disc space-y-2 pl-6 text-muted-foreground">
          <li>
            User accounts are retained for the duration of the account relationship plus up to 24
            months after account closure.
          </li>
          <li>Support tickets, correspondence, and chat transcripts may be retained up to 24 months.</li>
          <li>Application usage statistics and server logs may be retained up to 24 months.</li>
          <li>
            Email marketing data may be retained until You unsubscribe or up to 24 months from
            Your last engagement, whichever comes first.
          </li>
        </ul>
        <p>
          We may retain Personal Data longer where required by law, needed for legal claims,
          requested by You, or present in backup systems scheduled for routine deletion. When
          retention periods expire, We securely delete or anonymize Personal Data.
        </p>
      </Section>

      <Section title="Transfer of Your Personal Data">
        <p>
          Your information, including Personal Data, is processed at the Company's operating
          offices and in other places where the parties involved in the processing are located. It
          may therefore be transferred to and maintained on computers located outside of Your
          jurisdiction where data protection laws may differ.
        </p>
        <p>
          Where required by applicable law, We will ensure that international transfers of Your
          Personal Data are subject to appropriate safeguards and supplementary measures where
          appropriate.
        </p>
      </Section>

      <Section title="Delete Your Personal Data">
        <p>
          You have the right to delete or request that We assist in deleting the Personal Data that
          We have collected about You. Our Service may give You the ability to delete certain
          information from within the Service.
        </p>
        <p>
          You may also update, amend, or delete Your information at any time by signing in to Your
          Account and visiting the relevant account settings section, or by contacting Us to
          request access to, correction of, or deletion of Personal Data that You have provided.
        </p>
        <p>
          Please note that We may need to retain certain information where We have a legal
          obligation or lawful basis to do so.
        </p>
      </Section>

      <Section title="Disclosure of Your Personal Data">
        <ul className="list-disc space-y-2 pl-6 text-muted-foreground">
          <li>
            If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data
            may be transferred. We will provide notice before the transfer becomes effective.
          </li>
          <li>
            Under certain circumstances, the Company may be required to disclose Your Personal Data
            if required by law or in response to valid requests by public authorities.
          </li>
          <li>
            We may disclose Personal Data in the good faith belief that doing so is necessary to
            comply with law, protect the rights or property of the Company, investigate wrongdoing,
            protect the safety of users or the public, or protect against legal liability.
          </li>
        </ul>
      </Section>

      <Section title="Security of Your Personal Data">
        <p>
          The security of Your Personal Data is important to Us, but no method of transmission over
          the Internet or method of electronic storage is 100% secure. While We strive to use
          commercially reasonable means to protect Your Personal Data, We cannot guarantee its
          absolute security.
        </p>
      </Section>

      <Section title="Detailed Information on the Processing of Your Personal Data">
        <p>
          The Service Providers We use may have access to Your Personal Data. These third-party
          vendors collect, store, use, process, and transfer information about Your activity on Our
          Service in accordance with their own privacy policies.
        </p>
        <h3 className="font-semibold text-foreground">Email Marketing</h3>
        <p>
          We may use Your Personal Data to contact You with newsletters, marketing or promotional
          materials, and other information that may be of interest to You. You may opt out of
          receiving any, or all, of these communications by following the unsubscribe link or
          instructions in any email We send or by contacting Us.
        </p>
        <p>
          We may use email marketing service providers such as Mailgun and Hubspot to manage and
          send emails to You.
        </p>
      </Section>

      <Section title="CCPA/CPRA Privacy Notice (California Privacy Rights)">
        <p>
          This privacy notice section for California residents supplements the information
          contained in Our Privacy Policy and applies solely to visitors, users, and others who
          reside in the State of California.
        </p>
        <p>
          We may collect or have collected the following categories of personal information from
          California residents within the last twelve months:
        </p>
        <ul className="list-disc space-y-2 pl-6 text-muted-foreground">
          <li>Category A: Identifiers - Collected: Yes.</li>
          <li>Category B: California customer records information - Collected: Yes.</li>
          <li>Category C: Protected classifications - Collected: No.</li>
          <li>Category D: Commercial information - Collected: No.</li>
          <li>Category E: Biometric information - Collected: No.</li>
          <li>Category F: Internet or network activity - Collected: Yes.</li>
          <li>Category G: Geolocation data - Collected: No.</li>
          <li>Category H: Sensory data - Collected: No.</li>
          <li>Category I: Professional or employment-related information - Collected: No.</li>
          <li>Category J: Non-public education information - Collected: No.</li>
          <li>Category K: Inferences - Collected: No.</li>
          <li>Category L: Sensitive personal information - Collected: No.</li>
        </ul>
        <p>
          Under CCPA/CPRA, Personal Information does not include publicly available information
          from government records, deidentified or aggregated consumer information, or information
          excluded from the law's scope such as certain HIPAA, GLBA, FCRA, and similar records.
        </p>
        <p>
          We obtain personal information directly from You, indirectly from observing Your
          activity, automatically through technologies on Your Device, and from Service Providers.
        </p>
        <p>
          We may use or disclose personal information for business or commercial purposes such as
          operating the Service, providing support, fulfilling requests, responding to law
          enforcement, internal administration, auditing, and detecting security incidents or other
          harmful activity.
        </p>
        <p>
          We may use or disclose, and may have used or disclosed in the last twelve months, the
          following categories for business or commercial purposes: Category A, Category B, and
          Category F.
        </p>
        <p>
          We may share, and may have shared in the last twelve months, personal information with
          Service Providers, affiliates, business partners, and third-party vendors to whom You or
          Your agents authorize Us to disclose information in connection with products or services
          We provide to You.
        </p>
        <p>
          We do not "sell" or "share" information as most people commonly understand those terms,
          meaning We do not and will not disclose Personal Information in direct exchange for money
          or some other form of payment. However, certain disclosures of Category A, Category B,
          and Category F information may be considered a "sale" or "sharing" under CCPA/CPRA.
        </p>
        <p>
          We do not knowingly collect personal information from minors under the age of 16 through
          our Service, and We do not knowingly sell the personal information of consumers We
          actually know are under 16 without the required affirmative authorization.
        </p>
      </Section>

      <Section title="Your Rights under the CCPA/CPRA">
        <p>If You are a California resident, You have the following rights:</p>
        <ul className="list-disc space-y-2 pl-6 text-muted-foreground">
          <li>The right to notice about categories of Personal Information collected and used.</li>
          <li>The right to know or access what information We collected, used, shared, or sold.</li>
          <li>The right to opt out of the sale or sharing of Personal Information.</li>
          <li>The right to correct inaccurate Personal Information.</li>
          <li>The right to limit use and disclosure of certain sensitive Personal Information.</li>
          <li>
            The right to request deletion of Personal Information, subject to certain exceptions.
          </li>
          <li>
            The right not to be discriminated against for exercising any of these privacy rights.
          </li>
        </ul>
        <p>
          To exercise any of these rights, and if You are a California resident, You can contact
          Us by email at admin@sfluv.org or by visiting www.sfluv.org/contact.
        </p>
      </Section>

      <Section title="Do Not Sell or Share My Personal Information">
        <p>
          You have the right to opt out of the "sale" of Your personal information as defined by
          CCPA/CPRA. Once We receive and confirm a verifiable consumer request from You, We will
          stop selling or sharing Your Personal Information as required by law.
        </p>
      </Section>

      <Section title="Limit the Use or Disclosure of My Sensitive Personal Information">
        <p>
          If You are a California resident, You have the right to limit the use and disclosure of
          certain sensitive personal information to uses necessary to perform the services or
          provide the goods reasonably expected by an average consumer who requests them.
        </p>
        <p>
          We collect, use and disclose sensitive personal information only in ways that are
          necessary to provide the Service. For more information, please contact Us using the
          methods listed below.
        </p>
      </Section>

      <Section title="Do Not Track and California Privacy Disclosures">
        <p>
          Our Service does not respond to Do Not Track signals. However, some third-party websites
          may keep track of Your browsing activities. You can set Your browser preferences to
          inform websites that You do not want to be tracked.
        </p>
        <p>
          California residents with an established business relationship with Us may request
          information once a year about sharing Personal Data with third parties for direct
          marketing purposes. California residents under the age of 18 may also request removal of
          publicly posted content or information, subject to applicable limits and exceptions.
        </p>
      </Section>

      <Section title="Children's Privacy">
        <p>
          Our Service does not address anyone under the age of 16. We do not knowingly collect
          personally identifiable information from anyone under 16. If You are a parent or guardian
          and You are aware that Your child has provided Us with Personal Data, please contact Us.
        </p>
        <p>
          If We become aware that We have collected Personal Data from anyone under 16 without
          verification of parental consent, We take steps to remove that information from Our
          servers.
        </p>
      </Section>

      <Section title="Links to Other Websites">
        <p>
          Our Service may contain links to other websites that are not operated by Us. If You click
          on a third-party link, You will be directed to that third party's site. We strongly
          advise You to review the Privacy Policy of every site You visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content, privacy policies or
          practices of any third-party sites or services.
        </p>
      </Section>

      <Section title="Changes to this Privacy Policy">
        <p>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by
          posting the new Privacy Policy on this page and updating the "Last updated" date at the
          top of this Privacy Policy.
        </p>
        <p>
          We may also let You know via email and/or a prominent notice on Our Service before the
          change becomes effective. You are advised to review this Privacy Policy periodically for
          any changes. Changes to this Privacy Policy are effective when they are posted on this
          page.
        </p>
      </Section>

      <Section title="Contact Us">
        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul className="list-disc space-y-2 pl-6 text-muted-foreground">
          <li>By email: admin@sfluv.org</li>
          <li>By visiting this page on our website: www.sfluv.org/contact</li>
        </ul>
      </Section>
    </PolicyPageShell>
  )
}
